-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Oct 21, 2021 at 07:49 PM
-- Server version: 10.4.20-MariaDB
-- PHP Version: 8.0.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `quantiply`
--

-- --------------------------------------------------------

--
-- Table structure for table `astonomy`
--

CREATE TABLE `astonomy` (
  `id` int(11) NOT NULL,
  `date` varchar(50) NOT NULL,
  `media_type` varchar(20) NOT NULL,
  `service_version` varchar(5) NOT NULL,
  `title` varchar(255) NOT NULL,
  `url` varchar(455) NOT NULL,
  `explanation` text NOT NULL,
  `hdurl` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `astonomy`
--

INSERT INTO `astonomy` (`id`, `date`, `media_type`, `service_version`, `title`, `url`, `explanation`, `hdurl`) VALUES
(1, '2020-12-22', 'image', 'v1', 'Trifid Pillars and Jets', 'https://apod.nasa.gov/apod/image/2012/Trifid_HubbleMehla_1080.jpg', 'Dust pillars are like interstellar mountains.  They survive because they are more dense than their surroundings, but they are being slowly eroded away by a hostile environment.  Visible in the featured picture is the end of a huge gas and dust pillar in the Trifid Nebula (M20), punctuated by a smaller pillar pointing up and an unusual jet pointing to the left.  Many of the dots are newly formed low-mass stars. A star near the small pillar\'s end is slowly being stripped of its accreting gas by radiation from a tremendously brighter star situated off the top of the image.  The jet extends nearly a light-year and would not be visible without external illumination.  As gas and dust evaporate from the pillars, the hidden stellar source of this jet will likely be uncovered, possibly over the next 20,000 years.   Growing Gallery: Notable images of the Great Conjunction submitted to APOD', NULL),
(2, '2020-12-23', 'image', 'v1', 'Jupiter Meets Saturn: A Red Spotted Great Conjunction', 'https://apod.nasa.gov/apod/image/2012/GreatConjunction_Peach_960.jpg', 'It was time for their close-up. Two days ago  Jupiter and Saturn passed a tenth of a degree from each other in what is known a Great Conjunction. Although the two planets pass each other on the sky every 20 years, this was the closest pass in nearly four centuries.  Taken early in day of the Great Conjunction, the featured multiple-exposure combination captures not only both giant planets in a single frame, but also Jupiter\'s four largest moons (left to right) Callisto, Ganymede, Io, and Europa --  and Saturn\'s largest moon Titan. If you look very closely, the clear Chilescope image even captures Jupiter\'s Great Red Spot. The now-separating planets can still be seen remarkably close -- within about a degree -- as they set just after the Sun, toward the west, each night for the remainder of the year.    Gallery: Notable images of the Great Conjunction submitted to APOD', NULL),
(3, '2020-12-24', 'image', 'v1', 'Portrait of NGC 1055', 'https://apod.nasa.gov/apod/image/2012/NGC1055_MP_1024c.jpg', 'Big, beautiful spiral galaxy NGC 1055 is a dominant member of a small galaxy group a mere 60 million light-years away toward the aquatically intimidating constellation Cetus. Seen edge-on, the island universe spans over 100,000 light-years, a little larger than our own Milky Way galaxy. The colorful, spiky stars decorating this cosmic portrait of NGC 1055 are in the foreground, well within the Milky Way. But the telltale pinkish star forming regions are scattered through winding dust lanes along the distant galaxy\'s thin disk. With a smattering of even more distant background galaxies, the deep image also reveals a boxy halo that extends far above and below the central bluge and disk of NGC 1055. The halo itself is laced with faint, narrow structures, and could represent the mixed and spread out debris from a satellite galaxy disrupted by the larger spiral some 10 billion years ago.', NULL),
(4, '2020-12-28', 'image', 'v1', 'M16: Inside the Eagle Nebula', 'https://apod.nasa.gov/apod/image/2012/EagleNebula_Paladini_960.jpg', 'From afar, the whole thing looks like an Eagle.  A closer look at the Eagle Nebula, however, shows the bright region is actually a window into the center of a larger dark shell of dust.  Through this window, a brightly-lit workshop appears where a whole open cluster of stars is being formed.  In this cavity tall pillars and round globules of dark dust and cold molecular gas remain where stars are still forming.  Already visible are several young bright blue stars whose light and winds are burning away and pushing back the remaining filaments and walls of gas and dust.  The Eagle emission nebula, tagged M16, lies about 6500 light years away, spans about 20 light-years, and is visible with binoculars toward the constellation of the Serpent (Serpens).  This picture involved over 12 hours of imaging and combines three specific emitted colors emitted by sulfur (colored as red), hydrogen (yellow), and oxygen (blue).   Gallery: Notable images of the recent Total Solar Eclipse submitted to APOD', NULL),
(5, '2020-12-18', 'image', 'v1', 'Diamond in the Sky', 'https://apod.nasa.gov/apod/image/2012/2020Dec14TSE_Ribas_IMG_9291c1024.jpg', 'When the shadow of the Moon raced across planet Earth\'s southern hemisphere on December 14, sky watchers along the shadow\'s dark central path were treated to the only total solar eclipse of 2020. During the New Moon\'s shadow play this glistening diamond ring was seen for a moment, even in cloudy skies. Known as the diamond ring effect, the transient spectacle actually happens twice. Just before and immediately after totality, a thin sliver of solar disk visible behind the Moon\'s edge creates the appearance of a shiny jewel set in a dark ring. This dramatic snapshot from the path of totality in northern Patagonia, Argentina captures this eclipse\'s second diamond ring, along with striking solar prominences lofted beyond the edge of the Moon\'s silhouette.', NULL),
(6, '2021-10-21', 'image', 'v1', 'SH2-308: The Dolphin-head Nebula', 'https://apod.nasa.gov/apod/image/2110/SH2-308NS_1024.jpg', 'Blown by fast winds from a hot, massive star, this cosmic bubble is huge. Cataloged as Sharpless 2-308 it lies some 5,000 light-years away toward the constellation of the Big Dog (Canis Major) and covers slightly more of the sky than a Full Moon. That corresponds to a diameter of 60 light-years at its estimated distance. The massive star that created the bubble, a Wolf-Rayet star, is the bright one near the center of the nebula. Wolf-Rayet stars have over 20 times the mass of the Sun and are thought to be in a brief, pre-supernova phase of massive star evolution. Fast winds from this Wolf-Rayet star create the bubble-shaped nebula as they sweep up slower moving material from an earlier phase of evolution. The windblown nebula has an age of about 70,000 years. Relatively faint emission captured by narrowband filters in the deep image is dominated by the glow of ionized oxygen atoms mapped to a blue hue. Presenting a mostly harmless outline, SH2-308 is also known as The Dolphin-head Nebula.', NULL),
(7, '2021-09-30', 'image', 'v1', 'The Hydrogen Clouds of M33', 'https://apod.nasa.gov/apod/image/2109/NebulaeTriangulumM33-1179.jpg', 'Gorgeous spiral galaxy M33 seems to have more than its fair share of glowing hydrogen gas. A prominent member of the local group of galaxies, M33 is also known as the Triangulum Galaxy and lies a mere 3 million light-years away.  Sprawling along loose spiral arms that wind toward the core, M33\'s giant HII regions are some of the largest known stellar nurseries, sites of the formation of short-lived but very massive stars. Intense ultraviolet radiation from the luminous massive stars ionizes the surrounding hydrogen gas and ultimately produces the characteristic red glow. To highlight the HII regions in this telescopic image, broadband data used to produce a color view of the galaxy were combined with narrowband data recorded through a hydrogen-alpha filter, transmitting the light of the strongest hydrogen emission line. Close-ups of cataloged HII regions appear in the sidebar insets. Use the individual reference number to find their location within the Triangulum Galaxy. For example, giant HII region NGC604 is identified in an inset on the right and appears at position number 15. That\'s about 4 o\'clock from galaxy center in this portrait of M33.', NULL),
(8, '2021-10-05', 'image', 'v1', 'Sunrise at the South Pole', 'https://apod.nasa.gov/apod/image/2110/SouthPoleSunRise_Wolf_960.jpg', 'Sunrise at the South Pole is different. Usually a welcome sight, it follows months of darkness -- and begins months of sunshine. At Earth\'s poles, it can take weeks for the Sun to rise, in contrast with hours at any mid-latitude location.  Sunrise at a pole is caused by the tilt of the Earth as it orbits the Sun, not by the rotation of the Earth.  Although at a pole, an airless Earth would first see first Sun at an equinox, the lensing effect of the Earth\'s atmosphere and the size of the solar disk causes the top of the Sun to appear about two-weeks early.  Pictured two weeks ago, the Sun peeks above the horizon of a vast frozen landscape at Earth\'s South Pole.  The true South Pole is just a few meters to the left of the communications tower. This polar sunrise capture was particularly photogenic as the Sun appeared capped by a green flash.', NULL),
(9, '2021-10-02', 'image', 'v1', 'A Light and Dusty Night', 'https://apod.nasa.gov/apod/image/2110/ArcsOfLightAndDust1024.jpg', 'Posing as a brilliant evening star, Venus lies near the western horizon in this southern hemisphere, early spring, night skyscape. To create the composite view exposures tracking the sky and fixed for the foreground were taken on September 25 from Cascavel in southern Brazil. In view after sunset, Venus appears immersed in a cone of zodiacal light, sunlight scattered from dust along the Solar System\'s ecliptic plane. In fact from either hemisphere of planet Earth, zodiacal light is most visible after sunset near a spring equinox, (or before sunrise near an autumn equinox) when its luminous arc lies at steep angles to the horizon. Extending above the sunset on this night, the zodiacal light reaches toward rich starfields and immense interstellar dust clouds in the bulge of the central Milky Way. Follow along the Milky Way from the central bulge back toward the horizon and you\'ll spot the closest star system to the Sun, Alpha Centauri, a mere 4.37 light-years away.', NULL),
(10, '2016-03-01', 'image', 'v1', 'NGC 3310: A Starburst Spiral Galaxy', 'https://apod.nasa.gov/apod/image/1603/ngc3310_gemini_960.jpg', 'The party is still going on in spiral galaxy NGC 3310.  Roughly 100 million years ago, NGC 3310 likely collided with a smaller galaxy causing the large spiral galaxy to light up with a tremendous burst of star formation.  The changing gravity during the collision created density waves that compressed existing clouds of gas and triggered the star-forming party.  The featured image from the Gemini North Telescope shows the galaxy in great detail, color-coded so that pink highlights gas while white and blue highlight stars.  Some of the star clusters in the galaxy are quite young, indicating that starburst galaxies may remain in star-burst mode for quite some time.  NGC 3310 spans about 50,000 light years, lies about 50 million light years away, and is visible with a small telescope towards the constellation of Ursa Major.', NULL),
(11, '2021-10-14', 'image', 'v1', 'NGC 7293: The Helix Nebula', 'https://apod.nasa.gov/apod/image/2110/Helix_Oxygen_crop2_1024.jpg', 'A mere seven hundred light years from Earth, toward the constellation Aquarius, a sun-like star is dying. Its last few thousand years have produced the Helix Nebula (NGC 7293), a well studied and nearby example of a Planetary Nebula, typical of this final phase of stellar evolution.  A total of 90 hours of exposure time have gone in to creating this expansive view of the nebula. Combining narrow band image data from emission lines of hydrogen atoms in red and oxygen atoms in blue-green hues, it shows remarkable details of the Helix\'s brighter inner region about 3 light-years across. The white dot at the Helix\'s center is this Planetary Nebula\'s hot, central star. A simple looking nebula at first glance, the Helix is now understood to have a surprisingly complex geometry.', NULL),
(12, '2021-10-01', 'image', 'v1', 'The Central Milky Way from Lagoon to Pipe', 'https://apod.nasa.gov/apod/image/2110/M8-Pipe_APOD_GabrielSantosSmall.jpg', 'Dark markings and colorful clouds inhabit this stellar landscape. The deep and expansive view spans more than 30 full moons across crowded star fields toward the center of our Milky Way Galaxy. Cataloged in the early 20th century by astronomer E. E. Barnard, the obscuring interstellar dust clouds seen toward the right include B59, B72, B77 and B78, part of the Ophiuchus molecular cloud complex a mere 450 light-years away. To the eye their combined shape suggests a pipe stem and bowl, and so the dark nebula\'s popular name is the Pipe Nebula. Three bright nebulae gathered on the left are stellar nurseries some 5,000 light-years distant toward the constellation Sagittarius. In the 18th century astronomer Charles Messier included two of them in his catalog of bright clusters and nebulae; M8, the largest of the triplet, and colorful M20 just above. The third prominent emission region includes NGC 6559 at the far left. Itself divided by obscuring dust lanes, M20 is also known as the Trifid. M8\'s popular moniker is the Lagoon Nebula.', NULL),
(13, '2021-06-02', 'image', 'v1', 'The Galactic Center in Stars, Gas, and Magnetism', 'https://apod.nasa.gov/apod/image/2106/gcenter_ChandraMeerKAT_960.jpg', 'What\'s going on near the center of our galaxy? To help find out, a newly detailed panorama has been composed that explores regions just above and below the galactic plane in radio and X-ray light.  X-ray light taken by the orbiting Chandra Observatory is shown in orange (hot), green (hotter), and purple (hottest) and superposed with a highly detailed image in radio waves, shown in gray, acquired by the MeerKAT array.  Interactions are numerous and complex. Galactic beasts such as expanding supernova remnants, hot winds from newly formed stars, unusually strong and colliding magnetic fields, and a central supermassive black hole are all battling in a space only 1000 light years across.  Thin bright stripes appear to result from twisting and newly connecting magnetic fields in colliding regions, creating an energetic type of inner galactic space weather with similarities to that created by our Sun.  Continued observations and study hold promise to not only shed more light on the history and evolution of our own galaxy -- but all galaxies.', NULL),
(14, '2021-07-06', 'image', 'v1', 'Saturn and Six Moons', 'https://apod.nasa.gov/apod/image/2107/SaturnAndMoons_Ranjbaran_960.jpg', 'How many moons does Saturn have? So far 82 have been confirmed, the smallest being only a fraction of a kilometer across. Six of its largest satellites can be seen here in a composite image with 13 short exposure of the bright planet, and 13 long exposures of the brightest of its faint moons, taken over two weeks last month.  Larger than Earth\'s Moon and even slightly larger than Mercury,Saturn\'s largest moon Titan has a diameter of 5,150 kilometers and was captured making nearly a complete orbit around its ringed parent planet.  Saturn\'s first known natural satellite, Titan was discovered in 1655 by Dutch astronomer Christiaan Huygens, in contrast with several newly discovered moons announced in 2019.  The trail on the far right belongs to Iapetus, Saturn\'s third largest moon. The radius of painted Iapetus\' orbit is so large that only a portion of it was captured here. Saturn leads Jupiter across the night sky this month, rising soon after sunset toward the southeast, and remaining visible until dawn.', NULL),
(15, '2021-10-18', 'image', 'v1', 'Earthshine Moon over Sicily', 'https://apod.nasa.gov/apod/image/2110/EarthshineSky_Giannobile_1212.jpg', 'Why can we see the entire face of this Moon?  When the Moon is in a crescent phase, only part of it appears directly illuminated by the Sun.  The answer is earthshine, also known as earthlight and the da Vinci glow.  The reason is that the rest of the Earth-facing Moon is slightly illuminated by sunlight first reflected from the Earth.  Since the Earth appears near full phase from the Moon -- when the Moon appears as a slight crescent from the Earth -- earthshine is then near its brightest.  Featured here in combined, consecutively-taken, HDR images taken earlier this month, a rising earthshine Moon was captured passing slowly near the planet Venus, the brightest spot near the image center.  Just above Venus is the star Dschubba (catalogued as Delta Scorpii), while the red star on the far left is Antares. The celestial show is visible through scenic cloud decks. In the foreground are the lights from Palazzolo Acreide, a city with ancient historical roots in Sicily, Italy.', NULL),
(16, '2021-05-04', 'image', 'v1', 'Space Station, Solar Prominences, Sun', 'https://apod.nasa.gov/apod/image/2105/IssSun_Ergun_960.jpg', 'That\'s no sunspot. It\'s the International Space Station (ISS) caught passing in front of the Sun. Sunspots, individually, have a dark central umbra, a lighter surrounding penumbra, and no Dragon capsules attached.  By contrast, the ISS is a complex and multi-spired mechanism, one of the largest and most complicated spacecraft ever created by humanity.  Also, sunspots circle the Sun, whereas the ISS orbits the Earth.  Transiting the Sun is not very unusual for the ISS, which orbits the Earth about every 90 minutes, but getting one\'s location, timing and equipment just right for a great image is rare.  The featured picture combined three images all taken from the same location and at nearly the same time. One image -- overexposed -- captured the faint prominences seen across the top of the Sun, a second image -- underexposed -- captured the complex texture of the Sun\'s chromosphere, while the third image -- the hardest to get -- captured the space station as it shot across the Sun in a fraction of a second.  Close inspection of the space station\'s silhouette even reveals a docked Dragon Crew capsule.', NULL),
(17, '2021-07-05', 'image', 'v1', 'IC 4592: The Blue Horsehead Reflection Nebula', 'https://apod.nasa.gov/apod/image/2107/ic4592_block_960.jpg', 'Do you see the horse\'s head?   What you are seeing is not the famous Horsehead nebula toward Orion but rather a fainter nebula that only takes on a familiar form with deeper imaging.  The main part of the here imaged molecular cloud complex is a reflection nebula cataloged as IC 4592.  Reflection nebulas are actually made up of very fine dust that normally appears dark but can look quite blue when reflecting the visible light of energetic nearby stars.  In this case, the source of much of the reflected light is a star at the eye of the horse.  That star is part of Nu Scorpii, one of the brighter star systems toward the constellation of the Scorpion (Scorpius).   A second reflection nebula dubbed IC 4601 is visible surrounding two stars to the right of the image center.   Almost Hyperspace: Random APOD Generator', NULL),
(18, '2021-01-31', 'image', 'v1', 'Asteroids in the Distance', 'https://apod.nasa.gov/apod/image/2101/AsteroidStreak_hst_960.jpg', 'Rocks from space hit Earth every day.  The larger the rock, though, the less often Earth is struck.  Many kilograms of space dust pitter to Earth daily. Larger bits appear initially as a bright meteor.  Baseball-sized rocks and ice-balls streak through our atmosphere daily, most evaporating quickly to nothing.  Significant threats do exist for rocks near 100 meters in diameter, which strike the Earth roughly every 1000 years.  An object this size could cause significant tsunamis were it to strike an ocean, potentially devastating even distant shores. A collision with a massive asteroid, over 1 km across, is more rare, occurring typically millions of years apart, but could have truly global consequences. Many asteroids remain undiscovered.  In the featured image, one such asteroid -- shown by the long blue streak -- was found by chance in 1998 by the Hubble Space Telescope. A collision with a large asteroid  would not affect Earth\'s orbit so much as raise dust that would affect Earth\'s climate.  One likely result is a global extinction of many species of life, possibly dwarfing the ongoing extinction occurring now.', NULL),
(19, '2021-07-25', 'image', 'v1', 'Crescent Neptune and Triton', 'https://apod.nasa.gov/apod/image/2107/neptunetriton_voyager_960.jpg', 'Gliding silently through the outer Solar System, the Voyager 2 spacecraft camera captured Neptune and Triton together in crescent phase.  The elegant picture of the ice-giant planet and its cloudy moon was taken from behind just after closest approach in 1989.  It could not have been taken from Earth because Neptune never shows a crescent phase to sunward Earth. The unusual vantage point also robs Neptune of its familiar blue hue, as sunlight seen from here is scattered forward, and so is reddened like the setting Sun.  Neptune is smaller but more massive than Uranus, has several dark rings, and emits more light than it receives from the Sun.', NULL),
(20, '2021-07-22', 'image', 'v1', 'NGC 7814: Little Sombrero with Supernova', 'https://apod.nasa.gov/apod/image/2107/NGC7814withSN2021rhuChart32_1024.jpg', 'Point your telescope toward the high flying constellation Pegasus and you can find this expanse of Milky Way stars and distant galaxies. NGC 7814 is centered in the pretty field of view that would almost be covered by a full moon. NGC 7814 is sometimes called the Little Sombrero for its resemblance to the brighter more famous M104, the Sombrero Galaxy. Both Sombrero and Little Sombrero are spiral galaxies seen edge-on, and both have extensive halos and central bulges cut by a thin disk with thinner dust lanes in silhouette. In fact, NGC 7814 is some 40 million light-years away and an estimated 60,000 light-years across. That actually makes the Little Sombrero about the same physical size as its better known namesake, appearing smaller and fainter only because it is farther away. In this telescopic view from July 17, NGC 7814 is hosting a newly discovered supernova, dominant immediately to the left of the galaxy\'s core. Cataloged as SN 2021rhu, the stellar explosion has been identified as a Type Ia supernova, useful toward calibrating the distance scale of the universe.', NULL),
(21, '2021-06-22', 'image', 'v1', 'HD 163296: Jet from a Star in Formation', 'https://apod.nasa.gov/apod/image/2106/HD163296_AlmaVlt_960.jpg', 'How are jets created during star formation? No one is sure, although recent images of the young star system HD 163296 are quite illuminating. The central star in the featured image is still forming but seen already surrounded by a rotating disk and an outward moving jet. The disk is shown in radio waves taken by the Atacama Large Millimeter Array (ALMA) in Chile, and show gaps likely created by the gravity of very-young planets.  The jet, shown in visible light taken by the Very Large Telescope (VLT, also in Chile), expels fast-moving gas -- mostly hydrogen -- from the disk center.  The system spans hundreds of times the Earth-Sun distance (au).  Details of these new observations are being interpreted to  bolster conjectures that the jets are generated and shaped, at least in part, by magnetic fields in the rotating disk. Future observations of HD 163296 and other similar star-forming systems may help fill in details.    Astrophysicists: Browse 2,500+ codes in the Astrophysics Source Code Library', NULL),
(22, '2021-06-04', 'image', 'v1', 'Blood Monster Moon', 'https://apod.nasa.gov/apod/image/2106/Lunareclipse_PinnaclesNationalPark1024.jpg', 'On May 26, the Full Flower Moon was caught in this single exposure as it emerged from Earth\'s shadow and morning twilight began to wash over the western sky. Posing close to the horizon near the end of totality, an eclipsed lunar disk is framed against bare oak trees at Pinnacles National Park in central California. The Earth\'s shadow isn\'t completely dark though. Faintly suffused with sunlight scattered by the atmosphere, the inner shadow gives the totally eclipsed moon a reddened appearance and the very dramatic popular moniker of a Blood Moon. Still, the monstrous visage of a gnarled tree in silhouette made this view of a total lunar eclipse even scarier.', NULL),
(23, '2021-06-20', 'image', 'v1', 'Sunrise Solstice over Stonehenge', 'https://apod.nasa.gov/apod/image/2106/StonehengeSun_alexander_960.jpg', 'Today the Sun reaches its northernmost point in planet Earth\'s sky.  Called a solstice, many cultures mark this date as a change of seasons -- from spring to summer in Earth\'s Northern Hemisphere and from fall to winter in Earth\'s Southern Hemisphere.  Precisely, the single time of solstice occurs today for some parts of the world, but tomorrow for other regions. The featured image was taken during the week of the 2008 summer solstice at Stonehenge in United Kingdom, and captures a picturesque sunrise involving fog, trees, clouds, stones placed about 4,500 years ago, and a 4.5 billion year old large glowing orb. Even given the precession of the Earth\'s rotational axis over the millennia, the Sun continues to rise over Stonehenge in an astronomically significant way.', NULL),
(24, '2021-06-23', 'video', 'v1', 'STARFORGE: A Star Formation Simulation', 'https://www.youtube.com/embed/BEckYJwCJno?rel=0', 'How do stars form?  Most form in giant molecular clouds located in the central disk of a galaxy.  The process is started, influenced, and limited by the stellar winds, jets, high energy starlight, and supernova explosions of previously existing stars. The featured video shows these complex interactions as computed by the STARFORGE simulation of a gas cloud 20,000 times the mass of our Sun. In the time-lapse visualization, lighter regions indicate denser gas, color encodes the gas speed (purple is slow, orange is fast), while dots indicate the positions of newly formed stars. As the video begins, a gas cloud spanning about 50 light years begins to condense under its own gravity.  Within 2 million years, the first stars form, while newly formed massive stars are seen to expel impressive jets. The simulation is frozen after 4.3 million years, and the volume then rotated to gain a three-dimensional perspective. Much remains unknown about star formation, including the effect of the jets in limiting the masses of subsequently formed stars.    Portal Universe: Random APOD Generator', NULL),
(25, '2021-10-02', 'image', 'v1', 'A Light and Dusty Night', 'https://apod.nasa.gov/apod/image/2110/ArcsOfLightAndDust1024.jpg', 'Posing as a brilliant evening star, Venus lies near the western horizon in this southern hemisphere, early spring, night skyscape. To create the composite view exposures tracking the sky and fixed for the foreground were taken on September 25 from Cascavel in southern Brazil. In view after sunset, Venus appears immersed in a cone of zodiacal light, sunlight scattered from dust along the Solar System\'s ecliptic plane. In fact from either hemisphere of planet Earth, zodiacal light is most visible after sunset near a spring equinox, (or before sunrise near an autumn equinox) when its luminous arc lies at steep angles to the horizon. Extending above the sunset on this night, the zodiacal light reaches toward rich starfields and immense interstellar dust clouds in the bulge of the central Milky Way. Follow along the Milky Way from the central bulge back toward the horizon and you\'ll spot the closest star system to the Sun, Alpha Centauri, a mere 4.37 light-years away.', NULL),
(26, '2021-10-19', 'image', 'v1', 'Palomar 6: Globular Star Cluster', 'https://apod.nasa.gov/apod/image/2110/Palomar6_Hubble_960.jpg', 'Where did this big ball of stars come from? Palomar 6 is one of about 200 globular clusters of stars that survive in our Milky Way Galaxy. These spherical star-balls are older than our Sun as well as older than most stars that orbit in our galaxy\'s disk.  Palomar 6 itself is estimated to be about 12.5 billion years old, so old that it is close to -- and so constrains -- the age of the entire universe.  Containing about 500,000 stars, Palomar 6 lies about 25,000 light years away, but not very far from our galaxy\'s center.  At that distance, this sharp image from the Hubble Space Telescope spans about 15 light-years.  After much study including images from Hubble, a leading origin hypothesis is that Palomar 6 was created -- and survives today -- in the central bulge of stars that surround the Milky Way\'s center, not in the distant galactic halo where most other globular clusters are now found.', NULL),
(27, '2021-10-16', 'image', 'v1', 'The Moona Lisa', 'https://apod.nasa.gov/apod/image/2110/Moonalisa_Example1024.jpg', 'Only natural colors of the Moon in planet Earth\'s sky appear in this creative visual presentation. Arranged as pixels in a framed image, the lunar disks were photographed at different times. Their varying hues are ultimately due to reflected sunlight affected by changing atmospheric conditions and the alignment geometry of Moon, Earth, and Sun. Here, the darkest lunar disks are the colors of earthshine. A description of earthshine, in terms of sunlight reflected by Earth\'s oceans illuminating the Moon\'s dark surface, was written over 500 years ago by Leonardo da Vinci.  But stand farther back from your monitor or just shift your gaze to the smaller versions of the image. You might also see one of da Vinci\'s most famous works of art.  Tonight: International Observe the Moon Night', NULL),
(28, '2021-06-03', 'image', 'v1', 'Millions of Stars in Omega Centauri', 'https://apod.nasa.gov/apod/image/2106/OmegaCent_LRGB_final1_1024.jpg', 'Globular star cluster Omega Centauri, also known as NGC 5139, is some 15,000 light-years away. The cluster is packed with about 10 million stars much older than the Sun within a volume about 150 light-years in diameter. It\'s the largest and brightest of 200 or so known globular clusters that roam the halo of our Milky Way galaxy. Though most star clusters consist of stars with the same age and composition, the enigmatic Omega Cen exhibits the presence of different stellar populations with a spread of ages and chemical abundances. In fact, Omega Cen may be the remnant core of a small galaxy merging with the Milky Way. Omega Centauri\'s red giant stars (with a yellowish hue) are easy to pick out in this sharp, color telescopic view.', NULL),
(29, '2021-10-08', 'image', 'v1', 'The Double Cluster in Perseus', 'https://apod.nasa.gov/apod/image/2110/doubleclustergroves1024.jpg', 'This pretty starfield spans about three full moons (1.5 degrees) across the heroic northern constellation of Perseus. It holds the famous pair of open star clusters, h and Chi Persei. Also cataloged as NGC 869 (top) and NGC 884, both clusters are about 7,000 light-years away and contain stars much younger and hotter than the Sun.  Separated by only a few hundred light-years, the clusters are both 13 million years young based on the ages of their individual stars, evidence that they were likely a product of the same star-forming region. Always a rewarding sight in binoculars, the Double Cluster is even visible to the unaided eye from dark locations. But a shroud of guitar strings was used to produce diffraction spikes on the colorful stars imaged in this vibrant telescopic view.   Global Moon Party:  Including APOD\'s Best Moon Images: Saturday, October 9', NULL),
(30, '2020-11-12', 'image', 'v1', 'Comet ATLAS and Orion\'s Belt', 'https://apod.nasa.gov/apod/image/2011/C2020M3Orion_CharlesBracken1024.jpg', 'With its closest approach to planet Earth scheduled for November 14, this Comet ATLAS (C/2020 M3) was discovered just this summer, another comet found by the NASA funded Asteroid Terrestrial-impact Last Alert System. It won\'t get as bright as Comet NEOWISE but it can still be spotted using binoculars, as it currently sweeps through the familiar constellation of Orion. This telephoto field from November 8, blends exposures registered on the comet with exposures registered on Orion\'s stars. It creates an effectively deep skyview that shows colors and details you can\'t quite see though, even in binoculars. The comet\'s telltale greenish coma is toward the upper left, above Orion\'s three belt stars lined-up across the frame below center. You\'ll also probably spot the Orion Nebula, and famous Horsehead Nebula in the stunning field of view. Of course one of Orion\'s belt stars is nearly 2,000 light-years away. On November 14, this comet ATLAS will fly a mere 2.9 light-minutes from Earth.', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `astonomy`
--
ALTER TABLE `astonomy`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `astonomy`
--
ALTER TABLE `astonomy`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
